connect:
  env:
    CONNECT_MYSQL_HOSTNAME: 'mysql.default' # host for openmrs mysql server
    CONNECT_MYSQL_USERNAME: root # username with replication rights for openmrs mysql server
    CONNECT_MYSQL_PASSWORD: password # 
    CONNECT_MYSQL_PORT: "3306"
    ANALYTICS_DB_HOST: "postgres.default"

jobmanager:
  env:
    FLINK_JOB_POSTGRES_URL: jdbc:postgresql://postgres.default:5432/analytics #JDBC url for sink database to used to store flatted data
    FLINK_JOB_POSTGRES_PASSWORD: password
    FLINK_JOB_POSTGRES_USER: analytics

parquetExport:
  enabled: false
  persistence:
    existingClaim: parquet-pvc
  env:
    LOCATION_TAG: location1
taskManager:
  processMemory: 4000m
  managedMemoryFraction: 0.7
  numberOfTaskSlots: 6
  resources: 
    limits:
      memory: 6000Mi
    requests:
      memory: 5000Mi
      cpu: 1000m
kafka:
  image: zouchine/debezium-kafka:latest
  persistence:
    existingClaim: kafka-pvc